# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake

# The command to remove a file.
RM = /apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /scratch/e802756/COURSES/SSPP/2022-2023/solutions

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /scratch/e802756/COURSES/SSPP/2022-2023/solutions

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/apps/software/CMake/3.15.3-GCCcore-8.3.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/e802756/COURSES/SSPP/2022-2023/solutions/CMakeFiles /scratch/e802756/COURSES/SSPP/2022-2023/solutions/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /scratch/e802756/COURSES/SSPP/2022-2023/solutions/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix_add

# Build rule for target.
matrix_add: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_add
.PHONY : matrix_add

# fast build rule for target.
matrix_add/fast:
	$(MAKE) -f introduction/CMakeFiles/matrix_add.dir/build.make introduction/CMakeFiles/matrix_add.dir/build
.PHONY : matrix_add/fast

#=============================================================================
# Target rules for targets named deviceQuery

# Build rule for target.
deviceQuery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deviceQuery
.PHONY : deviceQuery

# fast build rule for target.
deviceQuery/fast:
	$(MAKE) -f introduction/CMakeFiles/deviceQuery.dir/build.make introduction/CMakeFiles/deviceQuery.dir/build
.PHONY : deviceQuery/fast

#=============================================================================
# Target rules for targets named hello_world

# Build rule for target.
hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_world
.PHONY : hello_world

# fast build rule for target.
hello_world/fast:
	$(MAKE) -f introduction/CMakeFiles/hello_world.dir/build.make introduction/CMakeFiles/hello_world.dir/build
.PHONY : hello_world/fast

#=============================================================================
# Target rules for targets named reduction_v9

# Build rule for target.
reduction_v9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v9
.PHONY : reduction_v9

# fast build rule for target.
reduction_v9/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v9.dir/build.make reduction/CMakeFiles/reduction_v9.dir/build
.PHONY : reduction_v9/fast

#=============================================================================
# Target rules for targets named reduction_v10

# Build rule for target.
reduction_v10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v10
.PHONY : reduction_v10

# fast build rule for target.
reduction_v10/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v10.dir/build.make reduction/CMakeFiles/reduction_v10.dir/build
.PHONY : reduction_v10/fast

#=============================================================================
# Target rules for targets named reduction_v7

# Build rule for target.
reduction_v7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v7
.PHONY : reduction_v7

# fast build rule for target.
reduction_v7/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v7.dir/build.make reduction/CMakeFiles/reduction_v7.dir/build
.PHONY : reduction_v7/fast

#=============================================================================
# Target rules for targets named reduction_v6

# Build rule for target.
reduction_v6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v6
.PHONY : reduction_v6

# fast build rule for target.
reduction_v6/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v6.dir/build.make reduction/CMakeFiles/reduction_v6.dir/build
.PHONY : reduction_v6/fast

#=============================================================================
# Target rules for targets named reduction_v1

# Build rule for target.
reduction_v1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v1
.PHONY : reduction_v1

# fast build rule for target.
reduction_v1/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v1.dir/build.make reduction/CMakeFiles/reduction_v1.dir/build
.PHONY : reduction_v1/fast

#=============================================================================
# Target rules for targets named reduction_v8

# Build rule for target.
reduction_v8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v8
.PHONY : reduction_v8

# fast build rule for target.
reduction_v8/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v8.dir/build.make reduction/CMakeFiles/reduction_v8.dir/build
.PHONY : reduction_v8/fast

#=============================================================================
# Target rules for targets named reduction_v4

# Build rule for target.
reduction_v4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v4
.PHONY : reduction_v4

# fast build rule for target.
reduction_v4/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v4.dir/build.make reduction/CMakeFiles/reduction_v4.dir/build
.PHONY : reduction_v4/fast

#=============================================================================
# Target rules for targets named reduction_v0

# Build rule for target.
reduction_v0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v0
.PHONY : reduction_v0

# fast build rule for target.
reduction_v0/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v0.dir/build.make reduction/CMakeFiles/reduction_v0.dir/build
.PHONY : reduction_v0/fast

#=============================================================================
# Target rules for targets named reduction_v3

# Build rule for target.
reduction_v3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v3
.PHONY : reduction_v3

# fast build rule for target.
reduction_v3/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v3.dir/build.make reduction/CMakeFiles/reduction_v3.dir/build
.PHONY : reduction_v3/fast

#=============================================================================
# Target rules for targets named reduction_v2

# Build rule for target.
reduction_v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v2
.PHONY : reduction_v2

# fast build rule for target.
reduction_v2/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v2.dir/build.make reduction/CMakeFiles/reduction_v2.dir/build
.PHONY : reduction_v2/fast

#=============================================================================
# Target rules for targets named reduction_v5

# Build rule for target.
reduction_v5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reduction_v5
.PHONY : reduction_v5

# fast build rule for target.
reduction_v5/fast:
	$(MAKE) -f reduction/CMakeFiles/reduction_v5.dir/build.make reduction/CMakeFiles/reduction_v5.dir/build
.PHONY : reduction_v5/fast

#=============================================================================
# Target rules for targets named divergence

# Build rule for target.
divergence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 divergence
.PHONY : divergence

# fast build rule for target.
divergence/fast:
	$(MAKE) -f performance/CMakeFiles/divergence.dir/build.make performance/CMakeFiles/divergence.dir/build
.PHONY : divergence/fast

#=============================================================================
# Target rules for targets named bank_conflicts

# Build rule for target.
bank_conflicts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bank_conflicts
.PHONY : bank_conflicts

# fast build rule for target.
bank_conflicts/fast:
	$(MAKE) -f performance/CMakeFiles/bank_conflicts.dir/build.make performance/CMakeFiles/bank_conflicts.dir/build
.PHONY : bank_conflicts/fast

#=============================================================================
# Target rules for targets named memory_transfers

# Build rule for target.
memory_transfers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory_transfers
.PHONY : memory_transfers

# fast build rule for target.
memory_transfers/fast:
	$(MAKE) -f performance/CMakeFiles/memory_transfers.dir/build.make performance/CMakeFiles/memory_transfers.dir/build
.PHONY : memory_transfers/fast

#=============================================================================
# Target rules for targets named coalescing

# Build rule for target.
coalescing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coalescing
.PHONY : coalescing

# fast build rule for target.
coalescing/fast:
	$(MAKE) -f performance/CMakeFiles/coalescing.dir/build.make performance/CMakeFiles/coalescing.dir/build
.PHONY : coalescing/fast

#=============================================================================
# Target rules for targets named matrix_vector_cublas

# Build rule for target.
matrix_vector_cublas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_vector_cublas
.PHONY : matrix_vector_cublas

# fast build rule for target.
matrix_vector_cublas/fast:
	$(MAKE) -f matvec/CMakeFiles/matrix_vector_cublas.dir/build.make matvec/CMakeFiles/matrix_vector_cublas.dir/build
.PHONY : matrix_vector_cublas/fast

#=============================================================================
# Target rules for targets named matrix_vector_2d_block

# Build rule for target.
matrix_vector_2d_block: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_vector_2d_block
.PHONY : matrix_vector_2d_block

# fast build rule for target.
matrix_vector_2d_block/fast:
	$(MAKE) -f matvec/CMakeFiles/matrix_vector_2d_block.dir/build.make matvec/CMakeFiles/matrix_vector_2d_block.dir/build
.PHONY : matrix_vector_2d_block/fast

#=============================================================================
# Target rules for targets named matrix_vector_1thread

# Build rule for target.
matrix_vector_1thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_vector_1thread
.PHONY : matrix_vector_1thread

# fast build rule for target.
matrix_vector_1thread/fast:
	$(MAKE) -f matvec/CMakeFiles/matrix_vector_1thread.dir/build.make matvec/CMakeFiles/matrix_vector_1thread.dir/build
.PHONY : matrix_vector_1thread/fast

#=============================================================================
# Target rules for targets named matrix_vector_1d_block

# Build rule for target.
matrix_vector_1d_block: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_vector_1d_block
.PHONY : matrix_vector_1d_block

# fast build rule for target.
matrix_vector_1d_block/fast:
	$(MAKE) -f matvec/CMakeFiles/matrix_vector_1d_block.dir/build.make matvec/CMakeFiles/matrix_vector_1d_block.dir/build
.PHONY : matrix_vector_1d_block/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... matrix_add"
	@echo "... deviceQuery"
	@echo "... hello_world"
	@echo "... reduction_v9"
	@echo "... reduction_v10"
	@echo "... reduction_v7"
	@echo "... reduction_v6"
	@echo "... reduction_v1"
	@echo "... reduction_v8"
	@echo "... reduction_v4"
	@echo "... reduction_v0"
	@echo "... reduction_v3"
	@echo "... reduction_v2"
	@echo "... reduction_v5"
	@echo "... divergence"
	@echo "... bank_conflicts"
	@echo "... memory_transfers"
	@echo "... coalescing"
	@echo "... matrix_vector_cublas"
	@echo "... matrix_vector_2d_block"
	@echo "... matrix_vector_1thread"
	@echo "... matrix_vector_1d_block"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

